# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0004_auto_20171126_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('movie_thumbnail', models.URLField(null=True)),
                ('movie_name', models.CharField(default='', max_length=250, null=True)),
                ('plot', models.TextField()),
                ('genre', models.TextField()),
                ('director_name', models.CharField(max_length=50, null=True)),
                ('director_fbl', models.IntegerField(blank=True, null=True)),
                ('actor_1_name', models.CharField(max_length=50, null=True)),
                ('actor_1_fbl', models.IntegerField(blank=True, null=True)),
                ('actor_2_name', models.CharField(max_length=50, null=True)),
                ('actor_2_fbl', models.IntegerField(blank=True, null=True)),
                ('actor_3_name', models.CharField(max_length=50, null=True)),
                ('actor_3_fbl', models.IntegerField(blank=True, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
                ('duration', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
